"""Calendar templates shared across scenarios."""

from __future__ import annotations

CALENDAR_TEMPLATES: list[dict] = [
    {
        "key": "primary",
        "summary": "{email}",
        "description": "",
        "timezone": "UTC",
        "accessRole": "owner",
        "primary": True,
        "selected": True,
        "hidden": False,
        "colorId": "14",
    },
    {
        "key": "team",
        "summary": "NexusAI Engineering",
        "description": "Team rituals, sprint planning, and engineering meetings",
        "timezone": "UTC",
        "accessRole": "owner",
        "primary": False,
        "selected": True,
        "hidden": False,
        "colorId": "9",
        "acl_rules": [
            {"scopeType": "default", "role": "reader"},
        ],
    },
    {
        "key": "product",
        "summary": "Product Launch Calendar",
        "description": "Product, GTM, and customer milestones",
        "timezone": "UTC",
        "accessRole": "owner",
        "primary": False,
        "selected": True,
        "hidden": False,
        "colorId": "10",
    },
    {
        "key": "leadership",
        "summary": "Leadership Reviews",
        "description": "Exec briefings, staffing reviews, and cross-functional planning",
        "timezone": "UTC",
        "accessRole": "owner",
        "primary": False,
        "selected": False,
        "hidden": False,
        "colorId": "7",
    },
    {
        "key": "recruiting",
        "summary": "Hiring Pipeline",
        "description": "Interview loops, candidate debriefs, and recruiting syncs",
        "timezone": "UTC",
        "accessRole": "owner",
        "primary": False,
        "selected": True,
        "hidden": False,
        "colorId": "6",
    },
    {
        "key": "travel",
        "summary": "Travel",
        "description": "Flights, hotels, and conference travel",
        "timezone": "UTC",
        "accessRole": "owner",
        "primary": False,
        "selected": False,
        "hidden": False,
        "colorId": "11",
    },
    {
        "key": "family",
        "summary": "Family",
        "description": "Personal and family commitments",
        "timezone": "UTC",
        "accessRole": "owner",
        "primary": False,
        "selected": False,
        "hidden": False,
        "colorId": "12",
    },
    {
        "key": "holidays",
        "summary": "US Holidays",
        "description": "US federal holidays",
        "timezone": "UTC",
        "accessRole": "reader",
        "primary": False,
        "selected": True,
        "hidden": False,
        "colorId": "5",
        "acl_rules": [
            {"scopeType": "default", "role": "reader"},
        ],
    },
]
