"""Fixed and recurring events that anchor all core scenarios."""

from __future__ import annotations

NEEDLE_EVENTS: list[dict] = [
    {
        "summary": "Q2 Planning Kickoff",
        "calendar": "team",
        "description": "Finalize engineering priorities for Q2.",
        "location": "Zoom",
        "days_from_now": 2,
        "start_hour": 10,
        "duration_hours": 2,
        "attendees": ["sarah", "marcus", "priya", "james"],
    },
    {
        "summary": "Vendor Contract Renewal Deadline",
        "calendar": "product",
        "description": "Finalize renewal terms with VendorCo before EOD.",
        "location": "HQ Board Room",
        "days_from_now": 5,
        "start_hour": 16,
        "duration_hours": 1,
        "attendees": ["nina", "sarah", "helen"],
    },
    {
        "summary": "Leadership Weekly Prep",
        "calendar": "leadership",
        "description": "Prepare staffing updates and launch escalations before the exec review.",
        "location": "Board Room C",
        "days_from_now": 1,
        "start_hour": 8.5,
        "duration_hours": 1,
        "attendees": ["victor", "sarah", "omar"],
    },
    {
        "summary": "Final Candidate Debrief",
        "calendar": "recruiting",
        "description": "Consolidate interview feedback and decide on next steps for the candidate.",
        "location": "Meet Room A",
        "days_from_now": 3,
        "start_hour": 15,
        "duration_hours": 1,
        "attendees": ["maya", "marcus", "priya", "elena"],
    },
    {
        "summary": "Flight SFO -> JFK",
        "calendar": "travel",
        "description": "Conference travel to New York.",
        "location": "SFO Terminal 3",
        "days_from_now": 7,
        "start_hour": 8,
        "duration_hours": 6,
    },
    {
        "summary": "Postmortem: Checkout Incident",
        "calendar": "product",
        "description": "Review root cause and follow-up actions.",
        "location": "War Room",
        "days_from_now": -3,
        "start_hour": 14,
        "duration_hours": 1.5,
        "attendees": ["marcus", "priya", "james", "lisa"],
    },
    {
        "summary": "Family Dinner",
        "calendar": "family",
        "description": "Dinner reservation with family.",
        "location": "North Beach",
        "days_from_now": 1,
        "start_hour": 19,
        "duration_hours": 2,
        "attendees": ["zoe"],
    },
    {
        "summary": "Quarterly OKR Review",
        "calendar": "primary",
        "description": "Review progress against quarterly OKRs.",
        "location": "Home Office",
        "days_from_now": -1,
        "start_hour": 11,
        "duration_hours": 1,
        "attendees": ["sarah"],
    },
    {
        "summary": "Canceled: Architecture Sync",
        "calendar": "team",
        "description": "This sync was canceled after the async update landed.",
        "location": "Zoom",
        "days_from_now": -5,
        "start_hour": 15,
        "duration_hours": 1,
        "status": "cancelled",
    },
    {
        "summary": "Thanksgiving Day",
        "calendar": "holidays",
        "description": "US federal holiday",
        "location": "",
        "days_from_now": 30,
        "all_day": True,
        "duration_days": 1,
    },
]

RECURRING_NEEDLES: list[dict] = [
    {
        "summary": "Daily Standup",
        "calendar": "team",
        "description": "Daily engineering standup.",
        "location": "Zoom",
        "days_from_now": -2,
        "start_hour": 9,
        "duration_hours": 0.5,
        "recurrence": ["RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR;COUNT=20"],
        "attendees": ["sarah", "marcus", "priya", "james"],
    },
    {
        "summary": "Weekly 1:1 with Sarah",
        "calendar": "primary",
        "description": "Career growth and unblockers.",
        "location": "HQ 5F",
        "days_from_now": 0,
        "start_hour": 16,
        "duration_hours": 0.5,
        "recurrence": ["RRULE:FREQ=WEEKLY;COUNT=12"],
        "attendees": ["sarah"],
    },
    {
        "summary": "Leadership Staff Sync",
        "calendar": "leadership",
        "description": "Weekly update on launches, staffing, and risks.",
        "location": "Board Room C",
        "days_from_now": -1,
        "start_hour": 10,
        "duration_hours": 1,
        "recurrence": ["RRULE:FREQ=WEEKLY;BYDAY=TU;COUNT=10"],
        "attendees": ["victor", "sarah", "omar", "helen"],
    },
    {
        "summary": "Hiring Funnel Review",
        "calendar": "recruiting",
        "description": "Review open roles, candidate progression, and panel capacity.",
        "location": "Meet Room A",
        "days_from_now": -3,
        "start_hour": 11,
        "duration_hours": 0.75,
        "recurrence": ["RRULE:FREQ=WEEKLY;BYDAY=WE;COUNT=10"],
        "attendees": ["maya", "sarah", "omar"],
    },
    {
        "summary": "Gym Session",
        "calendar": "primary",
        "description": "Personal fitness routine.",
        "location": "Gym",
        "days_from_now": -1,
        "start_hour": 7,
        "duration_hours": 1,
        "recurrence": ["RRULE:FREQ=WEEKLY;BYDAY=MO,WE,FR;COUNT=18"],
    },
]
